services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:       #env variables for our backend, eg. accessed using process.end.DB
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_NAME: printing_db
      JWT_SECRET: supersecretkey  #key used for jwt token signing
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads  #uploaded file persistence, files stored in /app/uploads path of container mapped to /backend/uploads of current folder of our computer or vps

  postgres:       #env var postgres expects 
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: printing_db
    volumes:
      - postgres_data:/var/lib/postgresql/data   #vol_name:container_path (named volume declaration)
      - ./backend/db:/docker-entrypoint-initdb.d  #dockers postgrees img runs the files in /docker-entrypoint-initdb.d aitomatically when db is first created
                                                  #so init.sql will be stored there
volumes:               #this is basically variable declaration or resource definition 
  postgres_data:       #like this project uses a volume called postgres_data
